0-iam_betty

diff --git a/0x01-shell_permissions/0-iam_betty b/0x01-shell_permissions/0-iam_betty
--- a/0x01-shell_permissions/0-iam_betty
+++ b/0x01-shell_permissions/0-iam_betty
@@ -1,6 +1,12 @@
-#!/bin/bash/
-$ wc -l file
-su betty
-
+#!/bin/bash
+git add .
+echo 'betty:'
+read 0-iam_betty
+git commit -m '$0-iam_betty'
+result=$?
+if [ $result -eq 0 ]; then	
+git push
+else	
+echo 'Commit Failed
 
 
